### PR TITLE
Add support for B2 backend

### PR DESCRIPTION
**Pull request by harrim4n**

### CODE REVIEW

**Comment by zertrin** [comment]
Thanks, that's a very welcomed improvement. I will test it a bit on my side and then merge it.

**Comment by bhhaskin** [comment]
Any movement on this? B2 support would be very very nice.

**Comment by harrim4n** [comment]
@bhhaskin Just to make sure, you do know that you can already use B2 with this script right? I only added support for the size checking on B2.
To use it just set the DEST variable to 
`b2://some_account_id[:some_application_key]@some_bucket_name/some_dir`.
You can also set the application key using the FTP_PASSWORD variable.

This script simply passes this variable along to Duplicity, which (if you have the correct version installed), already supports B2 regardless.

**Comment by bhhaskin** [comment]
@harrim4n Yes, I do know that, but the size checking is what I like.

**Comment by zertrin** [comment]
Ah sorry, with Christmas and New year travels I forgot about it. Didn't find time to test but I think I can at least merge it into the `dev` branch for now. The diff seems clean :)

By the way I learned with your contribution a new interesting trick with `paste -sd+ | bc | numfmt --to=iec`. I didn't know the existence of paste and using it as a way to add numbers is quite nice.

**Pull request merged**
